logo: "/assets/images/logo.png"
description: 
url: "https://docs.imf.bz"

theme: just-the-docs
color_scheme: codered # Color scheme supports "light" (default) and "dark"

nav_enabled: false
search_enabled: false
aux_links: {}

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2025 International Meme Fund, a project by Jeet Industries Inc.'

ga_tracking: G-QV11R5T97S
ga_tracking_anonymize_ip: true 