title: IMF

logo: "/assets/images/logo.png"
description: IMF Credit is a credit cartel, a crypto-native credit union that unleashes the power of credit using any token as collateral.
url: "https://docs.imf.bz"

theme: just-the-docs
color_scheme: codered # Color scheme supports "light" (default) and "dark"

url: 
aux_links:
  IMF on GitHub: https://github.com/International-Meme-Fund/imf-docs
aux_links_new_tab: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_external_links:
  - title: Price impact calculator
    url: https://calc.imf.bz
    opens_in_new_tab: true
  - title: App v2.0.0
    url: https://app.imf.bz
    opens_in_new_tab: true
    
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2025 International Meme Fund.'

ga_tracking: G-QV11R5T97S
ga_tracking_anonymize_ip: true 