title: IMF

logo: "/assets/images/logo.png"
description: International Meme Fund (IMF) is crypto’s first credit union—built for the community, open to all assets.
url: "https://docs.imf.bz"

theme: just-the-docs
color_scheme: codered # Color scheme supports "light" (default) and "dark"

url: 
aux_links:
  IMF on GitHub: https://github.com/International-Meme-Fund/imf-docs
aux_links_new_tab: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_external_links:
  - title: App v2.0.0
    url: https://internationalmeme.fund
    
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2025 International Meme Fund.'

ga_tracking: G-QV11R5T97S
ga_tracking_anonymize_ip: true 